/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {
  /**
   * Rate dialog width
   */
  static readonly RATE_DIALOG_WIDTH: number = 140;
  /**
   * The surface width
   */
  static readonly SURFACE_WIDTH: number = 1920;
  /**
   * The surface height
   */
  static readonly SURFACE_HEIGHT: number = 1080;
  /**
   * The swiper duration
   */
  static readonly SWIPER_DURATION: number = 300;
  /**
   * The swiper cachedCount
   */
  static readonly CACHED_COUNT: number = 1;
  /**
   * The AVVolumePanel x coordinate in fullLandscapeScreen
   */
  static readonly AV_VOLUME_PANEL_X_IN_FULL: number = 82;
  /**
   * The AVVolumePanel y coordinate in fullLandscapeScreen
   */
  static readonly AV_VOLUME_PANEL_Y_IN_FULL: number = 320;
  /**
   * The AVVolumePanel x coordinate in default mode
   */
  static readonly AV_VOLUME_PANEL_X: number = 50;
  /**
   * The AVVolumePanel y coordinate in default mode
   */
  static readonly AV_VOLUME_PANEL_Y: number = 1070;
  /**
   * Initial volume setting
   */
  static readonly INITIAL_VOLUME: number = 5;
}